chatbot_name = "Папинбот"
print("Привет, я бот. Меня завут", chatbot_name,". А как тебя зовут?")
user_name = input()
print("Привет" + ' ' +  user_name)
print("Я повторяшка!")
text = input("Напиши что нибудь.",)
print("Да," + " " + user_name + " " + text)
text = input("Продолжим?",)
print("Да," + " " + user_name + " " + text)
text = input("Продолжим?",)
print("Да," + " " + user_name + " " + text)
text = input("Продолжим?",)
print("Да," + " " + user_name + " " + text)
text = input("Продолжим?",)
print("Да," + " " + user_name + " " + text)
text = input("Продолжим?",)
print("Да," + " " + user_name + " " + text)
